apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-optimizer-deployment
  labels:
    app: cash-optimizer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cash-optimizer
  template:
    metadata:
      labels:
        app: cash-optimizer
        label: label
    spec:
      containers:
      - name: cash-optimizer
        image: Uplift-0508/cash-optimizer
        ports:
        - containerPort: 8080